name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  mdtomlfmt:
    name: Generic format (md,toml)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run dprint
      run: |
        curl -fsSL https://dprint.dev/install.sh | sh
        /home/runner/.dprint/bin/dprint check

