name: Create release

on:
  pull_request:
    types:
      - closed

env:
  CARGO_TERM_COLOR: always

jobs:
  produce_binaries:
    name: Compile released binaries
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Archive release folder
        uses: actions/upload-artifact@v3
        with:
          name: release-folder
          path: target/release
          retention-days: 7

  create_release:
    name: Create from merged release branch
    uses: monero-rs/workflows/.github/workflows/create-release.yml@v2.0.2
    needs: produce_binaries
    with:
      artifact_name: release-folder
      files: |
         base58m/target/release/base58m

  release_to_crates:
    name: Publish the new release to crates.io
    needs: create_release
    uses: monero-rs/workflows/.github/workflows/release-to-crates-io.yml@v2.0.2
    secrets:
      cratesio_token: ${{ secrets.H4SH3D_CARGO_REGISTRY_TOKEN }}
